"""login-model-fix-v2

Revision ID: e8e0687c3ebc
Revises: d252c5f2f91b
Create Date: 2025-01-06 15:04:04.056511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e0687c3ebc'
down_revision: Union[str, None] = 'd252c5f2f91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
